export const QUERY_KEY = {
  LIST_POKEMONS: "LIST_POKEMONS",
  DETAIL_POKEMONS: "DETAIL_POKEMONS",
  DETAIL_POKEMONS_COLOR: "DETAIL_POKEMONS_COLOR",
  POKEMON_FAVORITE_LIST: "POKEMON_FAVORITE_LIST",
};
